# Generated by Django 5.0 on 2023-12-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="home_page",
            field=models.URLField(blank=True),
        ),
    ]
