# Generated by Django 5.0 on 2023-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_home_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(),
        ),
    ]
